---
- name: Harden login.defs
  ansible.builtin.lineinfile:
    dest: /etc/login.defs
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^ENCRYPT_METHOD"
      line: "ENCRYPT_METHOD    SHA512"  # Use SHA512 to hash passwords
    - regexp: "^MD5_CRYPT_ENAB"
      line: "MD5_CRYPT_ENAB    no"  # Don't use MD5 to hash passwords
    - regexp: "^SYSLOG_SG_ENAB"
      line: "SYSLOG_SG_ENAB    yes" # Log successful `newgrp` and `sg` commands
    - regexp: "^SYSLOG_SU_ENAB"
      line: "SYSLOG_SU_ENAB    yes" # Log successful `su` commands
    - regexp: "^LOG_OK_LOGINS"
      line: "LOG_OK_LOGINS     yes" # Log successful logins
    - regexp: "^LOG_UNKFAIL_ENAB"
      line: "LOG_UNKFAIL_ENAB     yes" # Enable display of unknown usernames in log (for visibility)
  notify: Restart ssh   # This handler runs only if change made
